### PR TITLE
adds the note about the unmaintained code and points to updated repo

### PR DESCRIPTION
**Pull request by avilatusell**

### CODE REVIEW

**Comment by davel** [comment]
We now have a couple of developers merging code in to @3scale's repository, perhaps this change is unnecessary after all?

**Comment by slobo** [comment]
Not to hijack the thread, but are there plans to make an official release on CPAN? Currently `carton` is unable to import this as I guess there is only an UNOFFICIAL release...

**Comment by mikz** [comment]
@slobo we are in the process of making the release. Might take few more days, sorry.
https://github.com/3scale/3scale_ws_api_for_perl/pull/5#issuecomment-273994568

**Comment by davel** [comment]
Code is still being maintained here.

**Pull request closed without merging**
